import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <div className="flex  p-5 w-full h-20 bg-gray-100 items-center justify-between">

        </div>
        <a href="/" className="text2x1">Navbar</a>
        
        <div className="flex gap-5 justify-center">
          <a href="/about" className="text-1">About</a>
          <a href="/profile" className="text-1">Profile</a>
        </div>
        {children}
      </body>
    </html>
  );
}
